// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auqxswyhdfcxbpwafwnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1cXhzd3loZGZjeGJwd2Fmd250Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MjkwMjgsImV4cCI6MjA2MzAwNTAyOH0.xhhrqiyQunrhKu2akyNJU3QW2OYHdBuW5E0GUJ6E_VI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);